name: "Test Module"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 4 * * 1"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: scionlab-module
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - run: nix-build "<nixpkgs/nixos>" -A vm --arg configuration ./tests/config.nix --show-trace
